/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.electrostore.view;




/**
 *
 * @author USER
 */
public class DashboardFrame extends javax.swing.JFrame {
    
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    // ADD THIS LINE HERE:
    private final com.electrostore.controller.ProductController productController = new com.electrostore.controller.ProductController();
    /**
     * Creates new form DashboardFrame
     */
    public DashboardFrame() {
      initComponents();
    tblInventory();
    
   pnlCustomers = new PanelCustomers();
    pnlMainContent.add(pnlCustomers, "pnlCardCustomers");
    
    pnlUsers = new PanelUsers();
    pnlMainContent.add(pnlUsers, "pnlCardUsers");
    
    pnlPOS = new PanelPOS();
    pnlMainContent.add(pnlPOS, "cardPOS");
    
    pnlReports = new PanelReports();
    pnlMainContent.add(pnlReports, "cardReports");

    // Add GUI designer inventory panel to CardLayout
    pnlMainContent.add(pnlCardInventory, "pnlCardInventory");

    pnlMainContent.revalidate();
    pnlMainContent.repaint(); 

    
       
    


    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnlSidebar = new javax.swing.JPanel();
        btnNavPOS = new javax.swing.JButton();
        btnNavInventory = new javax.swing.JButton();
        btnNavCustomers = new javax.swing.JButton();
        btnNavUsers = new javax.swing.JButton();
        btnNavReports = new javax.swing.JButton();
        btnNavLogout = new javax.swing.JButton();
        pnlMainContent = new javax.swing.JPanel();
        pnlCardInventory = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchInventory = new javax.swing.JTextField();
        btnSearchInventory = new javax.swing.JButton();
        btnAddProduct = new javax.swing.JButton();
        btnEditProduct = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();
        scrollInventory = new javax.swing.JScrollPane();
        tblInventory2 = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHeader.setBackground(new java.awt.Color(30, 41, 59));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ElectroStore Pro - Executive Dashboard");

        javax.swing.GroupLayout pnlHeaderLayout = new javax.swing.GroupLayout(pnlHeader);
        pnlHeader.setLayout(pnlHeaderLayout);
        pnlHeaderLayout.setHorizontalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(519, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(181, 181, 181))
        );
        pnlHeaderLayout.setVerticalGroup(
            pnlHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHeaderLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        getContentPane().add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        pnlSidebar.setBackground(new java.awt.Color(15, 23, 42));

        btnNavPOS.setBackground(new java.awt.Color(71, 85, 105));
        btnNavPOS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNavPOS.setForeground(new java.awt.Color(255, 255, 255));
        btnNavPOS.setText("POS / Checkout");
        btnNavPOS.setBorderPainted(false);
        btnNavPOS.setFocusPainted(false);
        btnNavPOS.setPreferredSize(new java.awt.Dimension(160, 40));
        btnNavPOS.addActionListener(this::btnNavPOSActionPerformed);

        btnNavInventory.setBackground(new java.awt.Color(71, 85, 105));
        btnNavInventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNavInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnNavInventory.setText("Inventory");
        btnNavInventory.setBorderPainted(false);
        btnNavInventory.setFocusPainted(false);
        btnNavInventory.setPreferredSize(new java.awt.Dimension(160, 40));
        btnNavInventory.addActionListener(this::btnNavInventoryActionPerformed);

        btnNavCustomers.setBackground(new java.awt.Color(71, 85, 105));
        btnNavCustomers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNavCustomers.setForeground(new java.awt.Color(255, 255, 255));
        btnNavCustomers.setText("Customers");
        btnNavCustomers.setBorderPainted(false);
        btnNavCustomers.setFocusPainted(false);
        btnNavCustomers.setPreferredSize(new java.awt.Dimension(160, 40));
        btnNavCustomers.addActionListener(this::btnNavCustomersActionPerformed);

        btnNavUsers.setBackground(new java.awt.Color(71, 85, 105));
        btnNavUsers.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNavUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnNavUsers.setText("Users");
        btnNavUsers.setBorderPainted(false);
        btnNavUsers.setFocusPainted(false);
        btnNavUsers.setPreferredSize(new java.awt.Dimension(160, 40));
        btnNavUsers.addActionListener(this::btnNavUsersActionPerformed);

        btnNavReports.setBackground(new java.awt.Color(71, 85, 105));
        btnNavReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNavReports.setForeground(new java.awt.Color(255, 255, 255));
        btnNavReports.setText("Reports");
        btnNavReports.setBorderPainted(false);
        btnNavReports.setFocusPainted(false);
        btnNavReports.setPreferredSize(new java.awt.Dimension(160, 40));
        btnNavReports.addActionListener(this::btnNavReportsActionPerformed);

        btnNavLogout.setBackground(new java.awt.Color(71, 85, 105));
        btnNavLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNavLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnNavLogout.setText("Logout");
        btnNavLogout.setBorderPainted(false);
        btnNavLogout.setFocusPainted(false);
        btnNavLogout.setPreferredSize(new java.awt.Dimension(160, 40));
        btnNavLogout.addActionListener(this::btnNavLogoutActionPerformed);

        javax.swing.GroupLayout pnlSidebarLayout = new javax.swing.GroupLayout(pnlSidebar);
        pnlSidebar.setLayout(pnlSidebarLayout);
        pnlSidebarLayout.setHorizontalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNavLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavPOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNavReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnlSidebarLayout.setVerticalGroup(
            pnlSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNavPOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnNavInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnNavCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnNavUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnNavReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnNavLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pnlMainContent.setBackground(new java.awt.Color(241, 245, 249));
        pnlMainContent.setLayout(new java.awt.CardLayout());

        pnlCardInventory.setBackground(new java.awt.Color(241, 245, 249));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 41, 59));
        jLabel4.setText("Inventory Management");

        txtSearchInventory.setPreferredSize(new java.awt.Dimension(200, 22));

        btnSearchInventory.setBackground(new java.awt.Color(71, 85, 105));
        btnSearchInventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchInventory.setText("Search");
        btnSearchInventory.addActionListener(this::btnSearchInventoryActionPerformed);

        btnAddProduct.setBackground(new java.awt.Color(37, 95, 235));
        btnAddProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduct.setText("+ Add Product");
        btnAddProduct.setFocusPainted(false);
        btnAddProduct.addActionListener(this::btnAddProductActionPerformed);

        btnEditProduct.setBackground(new java.awt.Color(30, 41, 59));
        btnEditProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnEditProduct.setText("Edit Product");
        btnEditProduct.setFocusPainted(false);
        btnEditProduct.addActionListener(this::btnEditProductActionPerformed);

        btnDeleteProduct.setBackground(new java.awt.Color(239, 68, 68));
        btnDeleteProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteProduct.setText("- Delete Product");
        btnDeleteProduct.setFocusPainted(false);
        btnDeleteProduct.addActionListener(this::btnDeleteProductActionPerformed);

        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Code", "Product Name", "Category", "Unit Price ($)", "Stock Qty", "Supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInventory);

        javax.swing.GroupLayout pnlCardInventoryLayout = new javax.swing.GroupLayout(pnlCardInventory);
        pnlCardInventory.setLayout(pnlCardInventoryLayout);
        pnlCardInventoryLayout.setHorizontalGroup(
            pnlCardInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCardInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCardInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCardInventoryLayout.createSequentialGroup()
                        .addComponent(txtSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchInventory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteProduct)))
                .addContainerGap())
            .addGroup(pnlCardInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCardInventoryLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pnlCardInventoryLayout.setVerticalGroup(
            pnlCardInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCardInventoryLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addGroup(pnlCardInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchInventory)
                    .addComponent(btnAddProduct)
                    .addComponent(btnEditProduct)
                    .addComponent(btnDeleteProduct))
                .addContainerGap(455, Short.MAX_VALUE))
            .addGroup(pnlCardInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlCardInventoryLayout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pnlMainContent.add(pnlCardInventory, "card2");

        tblInventory2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Product Code", "Product Name", "Category", "Unit Price ($)", "Stock Quantity", "Supplier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollInventory.setViewportView(tblInventory2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addComponent(pnlMainContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrollInventory))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlMainContent, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollInventory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavPOSActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) pnlMainContent.getLayout();
    cl.show(pnlMainContent, "cardPOS");
    }//GEN-LAST:event_btnNavPOSActionPerformed

    private void btnNavInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavInventoryActionPerformed
        // TODO add your handling code here:
           java.awt.CardLayout cl = (java.awt.CardLayout) pnlMainContent.getLayout();
    cl.show(pnlMainContent, "pnlCardInventory");
    }//GEN-LAST:event_btnNavInventoryActionPerformed

    private void btnNavReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavReportsActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl = (java.awt.CardLayout) pnlMainContent.getLayout();
    cl.show(pnlMainContent, "cardReports");
    }//GEN-LAST:event_btnNavReportsActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        // TODO add your handling code here:
           DialogProductForm dialog = new DialogProductForm(this, true);
    dialog.setVisible(true);
    
    if (dialog.isSavedSuccessfully()) {
        tblInventory(); // Automatically refresh table rows!
    // Reload data into tblInventory2
    }
    
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnEditProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProductActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblInventory.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a product from the table to edit.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

   int productId = (int) tblInventory.getValueAt(selectedRow, 0);
    String code = tblInventory.getValueAt(selectedRow, 1).toString();
    String name = tblInventory.getValueAt(selectedRow, 2).toString();
    String category = tblInventory.getValueAt(selectedRow, 3).toString();
    double price = Double.parseDouble(tblInventory.getValueAt(selectedRow, 4).toString());
    int qty = Integer.parseInt(tblInventory.getValueAt(selectedRow, 5).toString());
    String supplier = tblInventory.getValueAt(selectedRow, 6) != null ? tblInventory.getValueAt(selectedRow, 6).toString() : "";

    com.electrostore.model.Product productToEdit = new com.electrostore.model.Product(productId, code, name, category, price, qty, supplier);

    DialogProductForm dialog = new DialogProductForm(this, true, productToEdit);
    dialog.setVisible(true);

    if (dialog.isSavedSuccessfully()) {
        tblInventory();
    
    
    }
    }//GEN-LAST:event_btnEditProductActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed
        // TODO add your handling code here:
       int selectedRow = tblInventory.getSelectedRow();
    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a product to delete.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

      int productId = (int) tblInventory.getValueAt(selectedRow, 0);
    String productName = tblInventory.getValueAt(selectedRow, 2).toString();

    int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to delete product: " + productName + "?", 
        "Confirm Delete", 
        javax.swing.JOptionPane.YES_NO_OPTION, 
        javax.swing.JOptionPane.WARNING_MESSAGE
    );

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
         try {
            productController.deleteProduct(productId);
            javax.swing.JOptionPane.showMessageDialog(this, "Product deleted successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            tblInventory();
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error deleting product: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    
    }

        
    
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnSearchInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchInventoryActionPerformed
        // TODO add your handling code here:
       String keyword = txtSearchInventory.getText().trim();
    if (keyword.isEmpty()) {
        tblInventory();
        return;
    }

    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblInventory.getModel();
    model.setRowCount(0);  

    try {
        java.util.List<com.electrostore.model.Product> products = productController.searchProducts(keyword);
        for (com.electrostore.model.Product p : products) {
            model.addRow(new Object[]{
                p.getProductId(),
                p.getProductCode(),
                p.getProductName(),
                p.getCategory(),
                String.format("%.2f", p.getUnitPrice()),
                p.getStockQuantity(),
                p.getSupplier()
            });
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error searching products: " + ex.getMessage(), "Search Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSearchInventoryActionPerformed

    private void btnNavCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavCustomersActionPerformed
        // TODO add your handling code here:
         java.awt.CardLayout cl = (java.awt.CardLayout) pnlMainContent.getLayout();
    cl.show(pnlMainContent, "pnlCardCustomers");
    }//GEN-LAST:event_btnNavCustomersActionPerformed

    private void btnNavUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavUsersActionPerformed
        // TODO add your handling code here:
      
        java.awt.CardLayout cl = (java.awt.CardLayout) pnlMainContent.getLayout();
    cl.show(pnlMainContent, "pnlCardUsers");
    }//GEN-LAST:event_btnNavUsersActionPerformed

    private void btnNavLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavLogoutActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "Are you sure you want to log out of ElectroStore Pro?", 
        "Confirm Logout", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        this.dispose(); // Close current main window
        new com.electrostore.view.LoginForm().setVisible(true); // Re-open login window
    }
    }//GEN-LAST:event_btnNavLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardFrame().setVisible(true));
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnEditProduct;
    private javax.swing.JButton btnNavCustomers;
    private javax.swing.JButton btnNavInventory;
    private javax.swing.JButton btnNavLogout;
    private javax.swing.JButton btnNavPOS;
    private javax.swing.JButton btnNavReports;
    private javax.swing.JButton btnNavUsers;
    private javax.swing.JButton btnSearchInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlCardInventory;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainContent;
    private javax.swing.JPanel pnlSidebar;
    private javax.swing.JScrollPane scrollInventory;
    private javax.swing.JTable tblInventory;
    private javax.swing.JTable tblInventory2;
    private javax.swing.JTextField txtSearchInventory;
    // End of variables declaration//GEN-END:variables
private PanelCustomers pnlCustomers;
    private PanelUsers pnlUsers;
    private PanelPOS pnlPOS;
    private PanelReports pnlReports;
public void tblInventory() {
    javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblInventory.getModel();
    model.setRowCount(0);

    try {
        java.util.List<com.electrostore.model.Product> products = productController.getAllProducts();
        for (com.electrostore.model.Product p : products) {
            model.addRow(new Object[]{
                p.getProductId(),
                p.getProductCode(),
                p.getProductName(),
                p.getCategory(),
                String.format("%.2f", p.getUnitPrice()),
                p.getStockQuantity(),
                p.getSupplier()
            });
        }
    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading inventory: " + ex.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
}
}

   




